name: WitchKingOfAngmar
version: '${project.version}'
main: org.randomlima.witchkingofangmar.WitchKingOfAngmar
api-version: '1.20'
commands:
  angmarhelmet:
    description: A command that gives the player the Witch King of Angmar Helmet.
    usage: /<command>
